### ISSUE TITLE
Default Values

### ISSUE THREAD

**Issue by prowland** [vlucas/phpDataMapper#1]
It would be nice to have a way to define a default value for a field in the Mapper so that, if a value isn't set or doesn't exist for a record (on a new row, for instance) I can default it without having to manually set it every time.

**Comment by vlucas** [comment]
You can do this in the field definition on the Mapper:

```
class PostMapper extends phpDataMapper_Base
{
    // Specify the data source (table for SQL adapters)
    protected $_datasource = "blog_posts";

    // Define your fields as public class properties
    public $id = array('type' => 'int', 'primary' => true, 'serial' => true);
    public $title = array('type' => 'string', 'required' => true);
    public $body = array('type' => 'text', 'required' => true);
    public $status = array('type' => 'string', 'default' => 'draft');
    public $date_created = array('type' => 'datetime');
}
```

The 'status' field has a default value of 'draft' that will be automatically set upon insertion if the field value is empty or null.
