### ISSUE TITLE
many to many (n:m)

### ISSUE THREAD

**Issue by Koc** [vlucas/phpDataMapper#2]
There are only two types of relations here http://phpdatamapper.com/documentation/usage/table-relationships/

many-to-many doesn't supported? If no - when you be able make support this?

**Comment by vlucas** [comment]
It is not currently supported directly, no.

You can, however, setup a 'HasMany' relationship on two mappers that point to each other or an intermediary (joining) mapper to achieve the same effect.

All development thus far has been done in my spare time and driven by immediate need, and I have not encountered a situation yet where I have needed this in a project and was not able to find a suitable solution or workaround.

I don't have any current plans to develop this feature, as I am currently concentrating on other areas - namely integrating MongoDB as an adapter, and enhancing validation options. I will update this ticket if anything changes.

Feel free to contribute if you need this feature sooner:
http://phpdatamapper.com/contribute/
